require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "db/**"
    - bin/bundle
    - "**/vendor/**/*"
    - "**/*.gemspec"
    - "spec/**"  

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false