require: rubocop-rails

AllCops:
  Exclude:
    - "db/**"
    - bin/bundle
    - "**/vendor/**/*"
    - "**/*.gemspec"
    - "spec/**"
  NewCops: enable
  TargetRailsVersion: 7
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false

Layout/LineLength:
  Enabled: false

Rails:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false
